blog/urls.py
from django.conf.urls import patterns, url
from blog.views import IndexView, PostView


urlpatterns = patterns('',
    url(r'^/?$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', PostView.as_view(), name='post'),
)

django_test/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from class_based_auth_views.views import LoginView, LogoutView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls')),
    url(r'^login/$', LoginView.as_view(redirect_field_name=next), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
)

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    published = models.DateTimeField('date_published')
    
    def __unicode__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post)
    comment = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    
    def __unicode__(self):
        return(''.join((self.comment[:25],'...')))

blog/views.py
from django.shortcuts import render
from django.views import generic

from blog.models import Post, Comment
from blog.common.utils import LoginRequiredMixin

class IndexView(generic.ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'latest_post_list'
    
    def get_queryset(self):
        """return the 4 most recent posts"""
        return Post.objects.order_by('-published')[:4]
    
    
class PostView(LoginRequiredMixin, generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

blog/templates/base.html
<!DOCTYPE html>
<html>
	<head>
	{% block headcontent %}
		<title>Super Blog App!</title>
	{% endblock %}
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">

	</head>
	<body>
	{% if user.is_authenticated %}
		<a type="submit" class="btn-xs btn-default" href="{% url "logout" %}"/>logout</a>
	{% else %}
		<a href="{% url "login" %}?next=/blog/">Login</a>
	{% endif %}
	{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
    <p>{{ message }}</p>
    </div>
    {% endfor %}
</ul>
{% endif %}
	{% block bodycontent %}
		<p>If you see this, you haven't overridden bodycontent block in your template</p>
	{% endblock %}
	</body>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block headcontent %}
		<title>Blog Detail</title>
{% endblock %}
{% block bodycontent %}
<div class="container">
		<div class="jumbotron">
		<h1>{{ post.title }}</h1>
		<div>{{ post.body }}</div>
		</div>
		{% for comment in post.comment_set.all %}
		<div><blockquote><p>{{ comment.comment }}</p>
			<small>{{ comment.author }}</small>
			</blockquote>
		</div>
		
		{% endfor %}
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block headcontent %}
		<title>Blog Listing</title>
{% endblock %}
{% block bodycontent %}
		<div class="container">
		{% if latest_post_list %}
		{% for post in latest_post_list %}
		<div class="col-xs-6 col-md-3"><a href="/blog/{{ post.id }}"><h1>{{ post.title }}</h1></a>
			<p>{{ post.body }}</p>
		</div>
		{% endfor %}
		{% else %}
		<p>There ar no posts</p>
		{% endif %}
		</div>
{% endblock %}